# Generated by Django 4.1.7 on 2023-04-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_alter_studentinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harassment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=15, null=True)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('harassment_type', models.CharField(choices=[('Raging', 'Raging'), ('Sexual Harassment', 'Sexual Harassment'), ('Racial Harassment', 'Racial Harassment'), ('Gender-based Harassment', 'Gender-based Harassment'), ('LGBTQ+ Harassment', 'LGBTQ+ Harassment'), ('Disability Harassment', 'Disability Harassment'), ('Age-related Harassment', 'Age-related Harassment'), ('Religious Harassment', 'Religious Harassment')], max_length=30)),
                ('occurence_date', models.DateField()),
                ('accused_name', models.CharField(max_length=50)),
                ('accused_is', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Staff', 'Staff'), ('Gaurd', 'Gaurd'), ('Other', 'Other')], max_length=10)),
                ('accoused_detail', models.TextField()),
                ('description', models.TextField()),
                ('accept_status', models.BooleanField(default=False)),
                ('decline_status', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('hearing_date', models.DateField()),
                ('hearing_time', models.TimeField()),
                ('hearing_room', models.CharField(max_length=50)),
                ('proof_file', models.FileField(upload_to='Proof_file')),
                ('submit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_of', to='student.studentinfo')),
            ],
        ),
    ]
