# Generated by Django 4.1.7 on 2023-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harassment', '0002_alter_harassment_hearing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
