# Generated by Django 4.1.7 on 2023-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentinfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='signature',
            field=models.ImageField(null=True, upload_to='medai/signature'),
        ),
    ]
