# Generated by Django 4.1.7 on 2023-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentinfo_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
