# Generated by Django 4.1.7 on 2023-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
