# Generated by Django 4.1.7 on 2023-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_studentinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
